import type { ModelEntry } from "./types";

/**
 * Catalog of FREE, OPEN-SOURCE models — nothing here costs money and nothing
 * here has usage caps. Sizes are approximate for the recommended GGUF quant
 * (Q4_K_M unless noted) and are advisory: the Device Adviser recomputes fit
 * against the actual device probe.
 *
 * License notes: qwen2.5/mistral/nomic/bge/mxbai/phi/moondream are
 * Apache-2.0 / MIT; llama-family use the Llama Community license (free for
 * commercial use, attribution + <700M MAU rule); gemma uses the Gemma terms.
 * All are free to download and run.
 */
export const MODEL_CATALOG: ModelEntry[] = [
  // ── Tiny / on-device (phones, low-RAM laptops) ────────────────────────────
  {
    id: "qwen2.5:0.5b",
    name: "Qwen 2.5 0.5B",
    family: "Qwen2.5",
    params: "0.5B",
    license: "Apache-2.0",
    sizeGB: 0.4,
    minRamGB: 1.5,
    context: 32768,
    modalities: ["text"],
    tags: ["chat", "multilingual", "on-device"],
    gguf: true,
    webgpu: true,
    hfRepo: "onnx-community/Qwen2.5-0.5B-Instruct",
    recommendedQuant: "Q4_K_M",
    description: "Tiny but capable instruct model. Best pick for low-end phones and weak laptops.",
  },
  {
    id: "llama3.2:1b",
    name: "Llama 3.2 1B",
    family: "Llama",
    params: "1B",
    license: "Llama Community",
    sizeGB: 0.8,
    minRamGB: 2,
    context: 128000,
    modalities: ["text"],
    tags: ["chat", "on-device"],
    gguf: true,
    webgpu: true,
    hfRepo: "onnx-community/Llama-3.2-1B-Instruct",
    recommendedQuant: "Q4_K_M",
    description: "Very fast conversational model with a huge native context window.",
  },
  {
    id: "qwen2.5:1.5b",
    name: "Qwen 2.5 1.5B",
    family: "Qwen2.5",
    params: "1.5B",
    license: "Apache-2.0",
    sizeGB: 1.1,
    minRamGB: 2.5,
    context: 32768,
    modalities: ["text"],
    tags: ["chat", "multilingual", "code"],
    gguf: true,
    webgpu: true,
    hfRepo: "onnx-community/Qwen2.5-1.5B-Instruct",
    recommendedQuant: "Q4_K_M",
    description: "Balanced small model — noticeably better than 1B at no real cost.",
  },
  {
    id: "gemma2:2b",
    name: "Gemma 2 2B",
    family: "Gemma",
    params: "2B",
    license: "Gemma Terms",
    sizeGB: 1.6,
    minRamGB: 3,
    context: 8192,
    modalities: ["text"],
    tags: ["chat"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "Google's small model — surprisingly fluent summaries and Q&A.",
  },
  {
    id: "llama3.2:3b",
    name: "Llama 3.2 3B",
    family: "Llama",
    params: "3B",
    license: "Llama Community",
    sizeGB: 2.0,
    minRamGB: 3.5,
    context: 128000,
    modalities: ["text"],
    tags: ["chat", "tool-use", "multilingual"],
    gguf: true,
    webgpu: true,
    hfRepo: "onnx-community/Llama-3.2-3B-Instruct",
    recommendedQuant: "Q4_K_M",
    description: "The sweet spot for modest hardware: excellent instruction following.",
  },
  {
    id: "qwen2.5:3b",
    name: "Qwen 2.5 3B",
    family: "Qwen2.5",
    params: "3B",
    license: "Apache-2.0",
    sizeGB: 1.9,
    minRamGB: 3.5,
    context: 32768,
    modalities: ["text"],
    tags: ["chat", "multilingual", "code"],
    gguf: true,
    webgpu: true,
    hfRepo: "onnx-community/Qwen2.5-3B-Instruct",
    recommendedQuant: "Q4_K_M",
    description: "Strong multilingual all-rounder for a 3.5GB RAM budget.",
  },
  {
    id: "phi3.5:3.8b",
    name: "Phi-3.5 3.8B",
    family: "Phi",
    params: "3.8B",
    license: "MIT",
    sizeGB: 2.3,
    minRamGB: 4,
    context: 128000,
    modalities: ["text", "code"],
    tags: ["chat", "code", "reasoning"],
    gguf: true,
    webgpu: true,
    hfRepo: "onnx-community/Phi-3.5-mini-instruct",
    recommendedQuant: "Q4_K_M",
    description: "Microsoft's MIT-licensed model — punches well above its size on reasoning.",
  },

  // ── Mid (8–16 GB RAM laptops / desktops) ──────────────────────────────────
  {
    id: "mistral:7b",
    name: "Mistral 7B",
    family: "Mistral",
    params: "7B",
    license: "Apache-2.0",
    sizeGB: 4.1,
    minRamGB: 6,
    context: 32768,
    modalities: ["text"],
    tags: ["chat", "multilingual", "code"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "The classic Apache-2.0 7B — fast, permissive, universally supported.",
  },
  {
    id: "qwen2.5:7b",
    name: "Qwen 2.5 7B",
    family: "Qwen2.5",
    params: "7B",
    license: "Apache-2.0",
    sizeGB: 4.4,
    minRamGB: 6,
    context: 32768,
    modalities: ["text"],
    tags: ["chat", "multilingual", "code", "tool-use"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "The default recommendation for 8GB machines — best all-round 7B.",
  },
  {
    id: "qwen2.5-coder:7b",
    name: "Qwen 2.5 Coder 7B",
    family: "Qwen2.5-Coder",
    params: "7B",
    license: "Apache-2.0",
    sizeGB: 4.7,
    minRamGB: 7,
    context: 32768,
    modalities: ["text", "code"],
    tags: ["code"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "Purpose-built for coding — generation, explanation, and completion.",
  },
  {
    id: "llama3.1:8b",
    name: "Llama 3.1 8B",
    family: "Llama",
    params: "8B",
    license: "Llama Community",
    sizeGB: 4.9,
    minRamGB: 7,
    context: 128000,
    modalities: ["text"],
    tags: ["chat", "multilingual", "tool-use", "reasoning"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "The 8B heavyweight — best conversational quality at this size.",
  },
  {
    id: "deepseek-r1:7b",
    name: "DeepSeek R1 7B",
    family: "DeepSeek-R1",
    params: "7B",
    license: "MIT",
    sizeGB: 4.7,
    minRamGB: 7,
    context: 32768,
    modalities: ["text"],
    tags: ["reasoning", "math"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "MIT-licensed reasoning distilled model — thinks before answering.",
  },
  {
    id: "gemma2:9b",
    name: "Gemma 2 9B",
    family: "Gemma",
    params: "9B",
    license: "Gemma Terms",
    sizeGB: 5.5,
    minRamGB: 8,
    context: 8192,
    modalities: ["text"],
    tags: ["chat"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "Google's 9B — known for punchy, on-tone writing and Q&A.",
  },

  // ── Vision ────────────────────────────────────────────────────────────────
  {
    id: "moondream",
    name: "Moondream 2",
    family: "Moondream",
    params: "1.9B",
    license: "Apache-2.0",
    sizeGB: 1.7,
    minRamGB: 3.5,
    context: 2048,
    modalities: ["text", "vision"],
    tags: ["vision", "on-device"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "Tiny Apache-2.0 vision model — caption and answer questions about images.",
  },
  {
    id: "llama3.2-vision:11b",
    name: "Llama 3.2 Vision 11B",
    family: "Llama",
    params: "11B",
    license: "Llama Community",
    sizeGB: 7.1,
    minRamGB: 10,
    context: 128000,
    modalities: ["text", "vision"],
    tags: ["vision", "chat"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "Full multimodal chat — describe, analyse and reason about images.",
  },

  // ── Large (16–32 GB and up) ───────────────────────────────────────────────
  {
    id: "phi4:14b",
    name: "Phi-4 14B",
    family: "Phi",
    params: "14B",
    license: "MIT",
    sizeGB: 9.1,
    minRamGB: 12,
    context: 16384,
    modalities: ["text"],
    tags: ["reasoning", "math", "code"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "MIT-licensed reasoning powerhouse at 14B — near-absurd quality for its size.",
  },
  {
    id: "qwen2.5:14b",
    name: "Qwen 2.5 14B",
    family: "Qwen2.5",
    params: "14B",
    license: "Apache-2.0",
    sizeGB: 8.8,
    minRamGB: 12,
    context: 32768,
    modalities: ["text"],
    tags: ["chat", "code", "multilingual"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "Apache-2.0 14B — the best free model for 16GB machines, full stop.",
  },
  {
    id: "deepseek-r1:14b",
    name: "DeepSeek R1 14B",
    family: "DeepSeek-R1",
    params: "14B",
    license: "MIT",
    sizeGB: 9.0,
    minRamGB: 12,
    context: 32768,
    modalities: ["text"],
    tags: ["reasoning", "math"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "Bigger reasoning model — genuinely strong at math and logic puzzles.",
  },
  {
    id: "mistral-small:24b",
    name: "Mistral Small 24B",
    family: "Mistral",
    params: "24B",
    license: "Apache-2.0",
    sizeGB: 14.5,
    minRamGB: 18,
    context: 32768,
    modalities: ["text"],
    tags: ["chat", "code", "multilingual"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "Apache-2.0 24B — near-frontier quality, fits late-model laptops.",
  },
  {
    id: "qwen2.5:32b",
    name: "Qwen 2.5 32B",
    family: "Qwen2.5",
    params: "32B",
    license: "Apache-2.0",
    sizeGB: 19.6,
    minRamGB: 24,
    context: 32768,
    modalities: ["text"],
    tags: ["chat", "code", "multilingual"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "Flagship Apache-2.0 model for high-RAM desktops and workstations.",
  },
  {
    id: "mixtral:8x7b",
    name: "Mixtral 8x7B",
    family: "Mixtral",
    params: "46.7B MoE",
    license: "Apache-2.0",
    sizeGB: 26.0,
    minRamGB: 32,
    context: 32768,
    modalities: ["text"],
    tags: ["chat", "code", "multilingual"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "Sparse MoE — 46B total weights, 12B active per token. Runs fast on big RAM.",
  },
  {
    id: "llama3.1:70b",
    name: "Llama 3.1 70B",
    family: "Llama",
    params: "70B",
    license: "Llama Community",
    sizeGB: 40.0,
    minRamGB: 48,
    context: 128000,
    modalities: ["text"],
    tags: ["chat", "reasoning"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "Q4_K_M",
    description: "Workstation-class. Needs serious hardware — 32GB+ free RAM or a big GPU.",
  },

  // ── Embeddings / RAG ──────────────────────────────────────────────────────
  {
    id: "nomic-embed-text",
    name: "Nomic Embed Text",
    family: "Nomic",
    params: "137M",
    license: "Apache-2.0",
    sizeGB: 0.27,
    minRamGB: 1.5,
    context: 8192,
    modalities: ["embedding"],
    tags: ["rag", "embedding"],
    gguf: true,
    webgpu: true,
    hfRepo: "Xenova/nomic-embed-text-v1.5",
    recommendedQuant: "F16",
    description: "Small, strong embedding model — the default RAG companion.",
  },
  {
    id: "mxbai-embed-large",
    name: "MXBAI Embed Large",
    family: "MXBAI",
    params: "334M",
    license: "Apache-2.0",
    sizeGB: 0.7,
    minRamGB: 2,
    context: 512,
    modalities: ["embedding"],
    tags: ["rag", "embedding"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "F16",
    description: "High-quality English embeddings for retrieval and clustering.",
  },
  {
    id: "bge-m3",
    name: "BGE-M3",
    family: "BGE",
    params: "568M",
    license: "Apache-2.0",
    sizeGB: 1.2,
    minRamGB: 2.5,
    context: 8192,
    modalities: ["embedding"],
    tags: ["rag", "embedding", "multilingual"],
    gguf: true,
    webgpu: false,
    recommendedQuant: "F16",
    description: "Multilingual retrieval — dense, sparse, and multi-vector in one model.",
  },
  {
    id: "all-minilm",
    name: "All-MiniLM-L6-v2",
    family: "MiniLM",
    params: "23M",
    license: "MIT",
    sizeGB: 0.05,
    minRamGB: 0.75,
    context: 256,
    modalities: ["embedding"],
    tags: ["rag", "embedding", "on-device"],
    gguf: false,
    webgpu: true,
    hfRepo: "Xenova/all-MiniLM-L6-v2",
    recommendedQuant: "F32",
    description: "Tiny MIT embedding model — runs anywhere, even in-browser.",
  },
];

/** The device-capability tiers the Device Adviser computes. */
export const TIER_LABELS: Record<string, { label: string; blurb: string }> = {
  tiny: { label: "Tiny", blurb: "Phones and minimal laptops — on-device chat models only." },
  lite: { label: "Lite", blurb: "Entry laptops and tablets — small models run smoothly." },
  standard: { label: "Standard", blurb: "8GB-class machines — 7B–9B chat models are comfortable." },
  plus: { label: "Plus", blurb: "16GB-class machines — 14B models and code assistants." },
  pro: { label: "Pro", blurb: "24–32GB machines — 24B–32B models and MoE." },
  max: { label: "Max", blurb: "Workstations — 70B-class models and heavy RAG." },
};

export function catalogById(id: string): ModelEntry | undefined {
  return MODEL_CATALOG.find((m) => m.id === id);
}